### ISSUE TITLE
Nodejs12 Jenkins Agent fails pipeline run due to not enough memory

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-quickstarters#545]
**Describe the bug**
When using the nodejs12 jenkins agent in OpenShift4 and with the default resources defined (limit of mem of 2G) by ODS we run out of memory and pipeline fails.

**To Reproduce**
1. Provision a Nodejs12 related quickstarter
2. Pipeline fails with out of memory error

**Expected behavior**
Should have enough memory

**Affected version (please complete the following information):**
 - OpenShift: 4
 - OpenDevStack master 

**Additional context**
Change will only be provided in master, since nodejs12 is not default in 3.x

**Comment by gerardcl** [comment]
current given resouce values by default are:
```
    resources:
      limits:
        memory: "2Gi"
        cpu: "1"
      requests:
        memory: "1Gi"
        cpu: "100m"
```

we solve this by increasing 500Mi in memory resources side
